//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisableNvidiaTelemetry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DisableNvidiaTelemetry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Required.
        /// </summary>
        public static string AdministratorRequired {
            get {
                return ResourceManager.GetString("AdministratorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Disabled.
        /// </summary>
        public static string All_Disabled {
            get {
                return ResourceManager.GetString("All_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon made by freepik from www.flaticon.com.
        /// </summary>
        public static string ApplicationCredits {
            get {
                return ResourceManager.GetString("ApplicationCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is provided &apos;as-is&apos;, without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software. 
        ///
        ///Redistribution of this software is allowed, but the origin of this software must not be misrepresented; you must not claim that you wrote the original software..
        /// </summary>
        public static string ApplicationLicense {
            get {
                return ResourceManager.GetString("ApplicationLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic service startup disabled.
        /// </summary>
        public static string Automatic_service_startup_disabled {
            get {
                return ResourceManager.GetString("Automatic_service_startup_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic service startup enabled.
        /// </summary>
        public static string Automatic_service_startup_enabled {
            get {
                return ResourceManager.GetString("Automatic_service_startup_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic service startup failed.
        /// </summary>
        public static string Automatic_service_startup_failed {
            get {
                return ResourceManager.GetString("Automatic_service_startup_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap binoculars_256 {
            get {
                object obj = ResourceManager.GetObject("binoculars_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btn_donate_92x26 {
            get {
                object obj = ResourceManager.GetObject("btn_donate_92x26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates when program is opened.
        /// </summary>
        public static string Check_for_updates_on_startup {
            get {
                return ResourceManager.GetString("Check_for_updates_on_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Nvidia Telemetry.
        /// </summary>
        public static string Disable_Nvidia_Telemetry {
            get {
                return ResourceManager.GetString("Disable_Nvidia_Telemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable service startup failed.
        /// </summary>
        public static string Disable_service_startup_failed {
            get {
                return ResourceManager.GetString("Disable_service_startup_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable logging.
        /// </summary>
        public static string Enable_logging {
            get {
                return ResourceManager.GetString("Enable_logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to disable registry item.
        /// </summary>
        public static string Failed_to_disable_registry_item {
            get {
                return ResourceManager.GetString("Failed_to_disable_registry_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to disable task.
        /// </summary>
        public static string Failed_to_disable_task {
            get {
                return ResourceManager.GetString("Failed_to_disable_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable registry item.
        /// </summary>
        public static string Failed_to_enable_registry_item {
            get {
                return ResourceManager.GetString("Failed_to_enable_registry_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable task.
        /// </summary>
        public static string Failed_to_enable_task {
            get {
                return ResourceManager.GetString("Failed_to_enable_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find registry item.
        /// </summary>
        public static string Failed_to_find_registry_item {
            get {
                return ResourceManager.GetString("Failed_to_find_registry_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find service.
        /// </summary>
        public static string Failed_to_find_service {
            get {
                return ResourceManager.GetString("Failed_to_find_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find task.
        /// </summary>
        public static string Failed_to_find_task {
            get {
                return ResourceManager.GetString("Failed_to_find_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service.
        /// </summary>
        public static string Failed_to_start_service {
            get {
                return ResourceManager.GetString("Failed_to_start_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop service.
        /// </summary>
        public static string Failed_to_stop_service {
            get {
                return ResourceManager.GetString("Failed_to_stop_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found registry item.
        /// </summary>
        public static string Found_registry_item {
            get {
                return ResourceManager.GetString("Found_registry_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found service.
        /// </summary>
        public static string Found_service {
            get {
                return ResourceManager.GetString("Found_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found task.
        /// </summary>
        public static string Found_task {
            get {
                return ResourceManager.GetString("Found_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GitHub_Mark_Light_120px_plus {
            get {
                object obj = ResourceManager.GetObject("GitHub_Mark_Light_120px_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/NateShoffner/Disable-Nvidia-Telemetry.
        /// </summary>
        public static string GithubUrl {
            get {
                return ResourceManager.GetString("GithubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://nateshoffner.com.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap honeycomb_dark {
            get {
                object obj = ResourceManager.GetObject("honeycomb_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap honeycomb_gray {
            get {
                object obj = ResourceManager.GetObject("honeycomb_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging disabled on read-only device.
        /// </summary>
        public static string Logging_disabled_on_read_only_device {
            get {
                return ResourceManager.GetString("Logging_disabled_on_read_only_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Updates.
        /// </summary>
        public static string No_Updates {
            get {
                return ResourceManager.GetString("No_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates available..
        /// </summary>
        public static string No_updates_available_message {
            get {
                return ResourceManager.GetString("No_updates_available_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;business=nate.shoffner@gmail.com&amp;lc=US&amp;item_name=Disable%20Nvidia%20Telemetry&amp;currency_code=USD&amp;bn=PP%2dDonationsBF.
        /// </summary>
        public static string PaypalUrl {
            get {
                return ResourceManager.GetString("PaypalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run the program as administrator to continue..
        /// </summary>
        public static string Please_run_the_program_as_administrator_to_continue {
            get {
                return ResourceManager.GetString("Please_run_the_program_as_administrator_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable.
        /// </summary>
        public static string Portable {
            get {
                return ResourceManager.GetString("Portable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry item disabled.
        /// </summary>
        public static string Registry_item_disabled {
            get {
                return ResourceManager.GetString("Registry_item_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry item enabled.
        /// </summary>
        public static string Registry_item_enabled {
            get {
                return ResourceManager.GetString("Registry_item_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry item is.
        /// </summary>
        public static string Registry_item_is {
            get {
                return ResourceManager.GetString("Registry_item_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Later.
        /// </summary>
        public static string Restart_later {
            get {
                return ResourceManager.GetString("Restart_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Now.
        /// </summary>
        public static string Restart_now {
            get {
                return ResourceManager.GetString("Restart_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Windows restart is required in order for this change to take effect..
        /// </summary>
        public static string Restart_required_message {
            get {
                return ResourceManager.GetString("Restart_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        public static string Restart_requried {
            get {
                return ResourceManager.GetString("Restart_requried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run in background and disable Nvidia telemetry services and tasks:.
        /// </summary>
        public static string Run_in_background {
            get {
                return ResourceManager.GetString("Run_in_background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is.
        /// </summary>
        public static string Service_is {
            get {
                return ResourceManager.GetString("Service_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service started.
        /// </summary>
        public static string Service_started {
            get {
                return ResourceManager.GetString("Service_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service startup mode.
        /// </summary>
        public static string Service_startup_mode {
            get {
                return ResourceManager.GetString("Service_startup_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stopped.
        /// </summary>
        public static string Service_stopped {
            get {
                return ResourceManager.GetString("Service_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silently disabling telemetry registry items.
        /// </summary>
        public static string Silently_disabling_telemetry_registry_items {
            get {
                return ResourceManager.GetString("Silently_disabling_telemetry_registry_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silently disabling telemetry services.
        /// </summary>
        public static string Silently_disabling_telemetry_services {
            get {
                return ResourceManager.GetString("Silently_disabling_telemetry_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silently disabling telemetry tasks.
        /// </summary>
        public static string Silently_disabling_telemetry_tasks {
            get {
                return ResourceManager.GetString("Silently_disabling_telemetry_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/watch?v=cmkpISz6RvA.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task disabled.
        /// </summary>
        public static string Task_disabled {
            get {
                return ResourceManager.GetString("Task_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task enabled.
        /// </summary>
        public static string Task_enabled {
            get {
                return ResourceManager.GetString("Task_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is.
        /// </summary>
        public static string Task_is {
            get {
                return ResourceManager.GetString("Task_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Nvidia telemetry services and tasks on startup..
        /// </summary>
        public static string Task_scheduler_description {
            get {
                return ResourceManager.GetString("Task_scheduler_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Nvidia Telemetry.
        /// </summary>
        public static string Task_scheduler_name {
            get {
                return ResourceManager.GetString("Task_scheduler_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry Registry Items.
        /// </summary>
        public static string Telemetry_registry_items {
            get {
                return ResourceManager.GetString("Telemetry_registry_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry Services.
        /// </summary>
        public static string Telemetry_services {
            get {
                return ResourceManager.GetString("Telemetry_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry Tasks.
        /// </summary>
        public static string Telemetry_tasks {
            get {
                return ResourceManager.GetString("Telemetry_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string Update_available {
            get {
                return ResourceManager.GetString("Update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update is available, would you like to download it?.
        /// </summary>
        public static string Update_available_message {
            get {
                return ResourceManager.GetString("Update_available_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Error.
        /// </summary>
        public static string Update_error {
            get {
                return ResourceManager.GetString("Update_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while checking for updates..
        /// </summary>
        public static string Update_error_messsage {
            get {
                return ResourceManager.GetString("Update_error_messsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
